### ISSUE TITLE
Multiple AceLocale issues - 9.1.5 SexyRep 2021-11-11

### ISSUE THREAD

**Issue by fraerie** [neotron/WoW-SexyReputation#11]
5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Padding'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:232: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Width of the border.'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:225: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Edge size'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:224: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Border color'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:210: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'The border texture used for the background frame.'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:203: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Border Texture'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:202: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Background Color'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:186: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'The background texture used for the background frame.'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:179: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Background Texture'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:178: in main chunk

5x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Background Frame'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:171: in main chunk

**Comment by neotron** [comment]
Should be fixed in 2021-11-17
