### ISSUE TITLE
Error upon mouseover

### ISSUE THREAD

**Issue by Zallanon** [neotron/WoW-SexyReputation#12]
Message: ...ce\AddOns\SexyReputation\LibQTip-1.0\LibQTip-1.0-49.lua:538: attempt to call method 'GetBackdrop' (a nil value)
Time: Tue Nov 16 15:26:54 2021
Count: 1
Stack: ...ce\AddOns\SexyReputation\LibQTip-1.0\LibQTip-1.0-49.lua:538: attempt to call method 'GetBackdrop' (a nil value)

Locals:

**Comment by neotron** [comment]
Will take a look tomorrow.

**Comment by neotron** [comment]
Should be fixed in 2021-11-17
