### ISSUE TITLE
Session / Today numbers aren't right

### ISSUE THREAD

**Issue by NelsonMinar** [neotron/WoW-SexyReputation#2]
Welcome back! Love your addon and am glad to see Paragon support added.

I think there's a bug right now; my session and daily reputation changes aren't incrementing correctly. The absolute number is displayed correctly though. The increments are always too low but I can't work out a pattern. Like I got +20 five times for Rajani from Contracts (on my way to Exalted) and it will only show "+20" for Today.  Or I'll get +400 for Honorbound (already in Paragon) and it will display as +200. It's not simple, whatever it is.

Complicating factors... it's bonus XP month and I'm not sure if bonus gains are reported as multiple events or what. Also I'm running the Farmer addon which displays reputation games as scrolling text. I haven't tested without Farmer, if I do I'll report back.

**Comment by NelsonMinar** [comment]
I tested this more carefully with the Farmer add-on disabled. Testing was by doing quests and activities in Vale during an invasion, watching Rajani reputation. I'm about 19,000 on my way to Exalted.

Mostly the SexyReputation display just never updated. I'd get some rep from an activity and my character sheet rep would go up, but nothing would show up under "Session" or "Today". Also the ChocolatBar broker display number (watching the rep) didn't change, although the popup / mouseover values were correct. Anyway the whole thing acted like SexyReputation just never heard about the reputation increase events. Note this is a simpler problem that I'd initially reported; I thought I was seeing partial values posted. Maybe it's just all or nothing and I misunderstood.

I did a /reloadui and SexyReputation did get the next Rajani rep increase correctly (a quest turnin). But then two quest turnins right after registered nothing.

This all used to work, my guess is something in a recent update make it unreliable. Let me know if I can help you debug further.

**Comment by NelsonMinar** [comment]
One more observation, on an alt. I did some daily quests that give 3 bursts of Rep on completion: Tortollan Seekers, Zandalari Empire, and Guild (from the tabard). The Guild rep is updating right, but the factions aren't.

**Comment by neotron** [comment]
I'll take a lot, might be related to the paragon change perhaps.

**Comment by neotron** [comment]
Just a quick test definitely seems to work correctly for me. I did two world quests, giving 200 + 150 rep each and the first update was +350, and second one was +700. This includes both the display in the LDB container (I'm using ButtonBin) and the dropdown menu. Will do some more testing.

**Comment by neotron** [comment]
Did a third quest that gave 150 rep only. Didn't update. Strange...

**Comment by neotron** [comment]
Fixed in 8.3.0-4!

Change tracking now works for paragon reputations, and the bug with non-paragon ones is fixed.
