### ISSUE TITLE
localized string for newly added string is missing in other languages

### ISSUE THREAD

**Issue by mcc1** [neotron/WoW-SexyReputation#20]
Thanks, I've noticed you have merged my PR.
Because of the localized string is generated from wowace, and it seems you haven't update it.
Maybe you can add these strings to wowace localization page?

**Comment by neotron** [comment]
Yes, that is true and I forgot about how localization works since it had been so long since I did wow addon work.

**Comment by neotron** [comment]
I've updated the locales on ace so this should be fixed now.

**Comment by mcc1** [comment]
thanks!
