### ISSUE TITLE
Multiple missing entry errors

### ISSUE THREAD

**Issue by sirzooro** [neotron/WoW-SexyReputation#7]
I have some problems with addons after last WoW 9.1 update, so I checked script errors. I found multiple errors like one below, for different entry names. Trace starts in SexyReputations addon, so I suspect that error is in it, and not in Ace3.

```
Message: AceLocale-3.0: LibMagicUtil-1.0: Missing entry for 'Background Frame'
Time: Sat Jul  3 09:56:54 2021
Count: 1
Stack: AceLocale-3.0: LibMagicUtil-1.0: Missing entry for 'Background Frame'
[string "@Interface\AddOns\Ace3\AceLocale-3.0\AceLocale-3.0.lua"]:31: in function <...nterface\AddOns\Ace3\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0.lua"]:171: in main chunk

Locals: <none>
```

**Comment by b-morgan** [comment]
Same problem on Burning Crusade Classic 2.5.1. Ten errors all from LibMagicUtil-1.0. First and last below.
```
2x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Background Frame'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:171: in main chunk

2x AceLocale-3.0-6: LibMagicUtil-1.0-80200: Missing entry for 'Padding'
[string "@SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0-80200.lua"]:232: in main chunk
```
It appears that the L array isn't being loaded correctly (or from the right place) on enUS clients.

**Comment by amethystnw** [comment]
I'm also getting these these errors on 22 difference graphic elements: 

WoW version 9.1.0 (39653) released 8/2/2021
Sexy Reputation: 8/16/2021 release

Message: AceLocale-3.0: LibMagicUtil-1.0: Missing entry for 'Background Frame'
Time: Mon Aug 16 14:59:46 2021
Count: 1
Stack: AceLocale-3.0: LibMagicUtil-1.0: Missing entry for 'Background Frame'
[string "@Interface\AddOns\Ace3\AceLocale-3.0\AceLocale-3.0.lua"]:31: in function <...nterface\AddOns\Ace3\AceLocale-3.0\AceLocale-3.0.lua:29>
[string "@Interface\AddOns\SexyReputation\Libs\LibMagicUtil-1.0\LibMagicUtil-1.0\LibMagicUtil-1.0.lua"]:171: in main chunk

Locals: <none>

Other missing entries are:
-     Background texture
-     'The background texture used for the background frame.'
-     Background Color
-     Border Texture
-     'The border texture used for the background frame.'
-     Border Color
-     Edge Size
-     Width of the Border
-     Padding
-     'Number of pixels to insert between the background frame edge and the content.'
-     Tile Background
-     'Whether or not to tile the background texture.'
-     Tile Size
-     'The size in pixels of the background tiles.'
-     Bar Size
-     'Maximum number of bars'
-     Bar Height
-     Bar Width
-     Bar Scale
-     Bar Spacing
-     'The space in pixels between each bar.'

Aside from the errors on initial load, I don't see any issues with the display using Bazooka add on.

**Comment by neotron** [comment]
Should be fixed in 2021-11-17
